on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./
        id: hello
        env:
          EVERGREEN_AUTH: ${{ secrets.EVERGREEN_AUTH_DUMMY }}
